#!/usr/bin/bash

red='\e[31m'
green='\e[32m'
off='\e[0m'

if [[ -f $PATH/toilet ]]
then
	printf $green"Dependencies already installed!\n"$off
	sleep 2s
else
	printf $green"Installing dependencies...\n"$off
	apt update -y
	apt upgrade -y
	apt install toilet -y
fi

clear

toilet -f mono12 -F metal "Typer"
sleep 2s

printf $green"Simple program to simulate typing effect!\n\n"$off
sleep 2s

printf $green"Installing this program...\n\n"$off
for path in ${PATH//:/ }; do
    cp dist/typer $path
    
done
sleep 2s

printf $green"Successfully installed!\n\n"$off
sleep 2s

printf $red"Live demo:\n"$off
typer -s "I am a " programmer "web developer" "wannabe freelancer 🐸"

printf "\nType \e[1m${green}typer -h"$off" for help\n"
