#!/usr/bin/bash

red='\e[31m'
green='\e[32m'
off='\e[0m'

bin=/data/data/com.termux/files/usr/bin

if [[ -f $bin/toilet ]]
then
	printf $green"Dependencies already installed!\n"$off
	sleep 2s
else
	printf $green"Installing dependencies...\n"$off
	apt update
	apt install python figlet toilet -y
fi

clear

toilet -f mono12 -F metal "Typer"
sleep 2s

printf $green"Simple program to simulate typing effect!\n\n"$off
sleep 2s

printf $green"Installing this program...\n\n"$off
cp typer $bin
chmod +x $bin/typer
sleep 2s

printf $green"Successfully installed!\n\n"$off
sleep 2s

printf $red"Live demo:\n"$off
typer -s "I am a " programmer "web developer" "wannabe freelancer 🐸"

printf "\nType \e[1m${green}typer -h"$off" for help\n"
