#!/usr/bin/bash

red='\e[31m'
green='\e[32m'
off='\e[0m'

if [[ -f $PATH/toilet ]]
then
	printf $green"Dependencies already installed!\n"$off
else
	printf $green"Installing dependencies...\n"$off
	pkg update -y
	pkg upgrade -y
	pkg install toilet -y
fi

clear

toilet -f mono12 -F gay "Typer"

printf $green"Simple program to simulate typing effect!\n\n"$off
sleep 2s

printf $green"Installing this program...\n\n"$off
cp dist/typer $PATH
sleep 2s

printf $green"Successfully installed!\n\n"$off
sleep 2s

printf $red"Live demo:\n"$off
typer -s "I am a " programmer "web developer" "wannabe freelancer 🐸"

printf $green"Type \e[1mtyper -h"$green" for help"$off
